version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: abdullinilgiz/food_backend:latest
    volumes:
      - static:/backend_static/
      - media:/app/dishes/media
      - ../data/:/app/data/
    depends_on:
      - db
    env_file:
      - ../.env

  frontend:
    image: abdullinilgiz/food_frontend:latest
    volumes:
      - static:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - static:/static/
      - media:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
